### ISSUE TITLE
Electricity for cryogenic air separation

### ISSUE THREAD

**Issue by juliana-steinbach** [premise-community-scenarios/ammonia-prospective-scenarios#2]
In the inventory, the new activity "ammonia production, hydrogen from electrolysis" includes a new activity "nitrogen, from cryogenic distillation, gaseous" that does not contain any data regarding the electricity necessary for the air separation.

I see that no electricity is referenced in the original source, page 33 of the supplementary information of Planetary Boundaries Analysis of Low-Carbon Ammonia Production Routes, but could not find an explanation for it. Even though no compression is used in the activity, I would expect some electricity consumed in the process.

From what is available in the literature, the activity from"Nitrogen - air separation cryogenic" from ecoinvent contains 0.563kWh per kg of N2 and I have also seen values ranging from 0.42kWh to 0.37kWh per kg of N2 from the publication Potential for improving the energy efficiency of cryogenic air separation unit (ASU) using binary heat recovery cycles, page 230, table 2, from 2015.

Also, in case this is relevant, 0.177 kg hydrogen + 0.823 kg nitrogen represents the ideal HB process (no losses). ref: Life Cycle Assessment of Ammonia Production Methods, 2018.

**Comment by romainsacchi** [comment]
Hi @juliana-steinbach, I moved the ammonia inventories to premise directly. I cleaned them a little and replaced the nitrogen supply in the ammonia datasets with that from ecoinvent. The inventories will be part of `2.1.1.dev0` which I will release later today or tomorrow. So, if you update to that version, and also pull the latest from the ammonia repository, things should work and the electricity from cryogenic air separation should be properly accounted for. The LCIs are already available here: https://github.com/polca/premise/blob/master/premise/data/additional_inventories/lci-ammonia.xlsx
